auteur = "Mary Wollstonecraft Shelley"
author = "Mary Wollstonecraft Shelley"
bloctexte = "justify"
copyright = "CC BY-NC-SA"
couverture = "/uploads/illustration.jpg"
description = "A horrific story"
edition = "Édité par la classe ELD718-2024"
format = "portrait"
indentation = "oui"
isbn = ""
licence = "CC BY-NC-SA"
date = "2024"
logo = "images/logo2.webp"
marques = "crop"
mention = "Fabrique"
quatrieme = "oui"
readingtime = "oui"
search = false
soustitre = "Revised Edition, 1831"
titre = "Frankenstein, or the Modern Prometheus"
institution = "https://mmellet.github.io/ELD718_2024/images/logoUDS.png"
github = "https://mmellet.github.io/ELD718_2024/images/github.webp"
