audience = "adult"
author = "Mary Wollstonecraft Shelley"
bookid = ""
copyright = "CC BY-NC-SA"
date = "2024"
description = "A horrific story"
imgsize = "1200x q70"
logo = "/uploads/illustration.jpg"
publisher = "Fabrique ELD718 - 2024"
subject = ["horror", "frisson", "fantastique"]
subtitle = "Frankenstein, or the Modern Prometheus"
title = "Revised Edition, 1831"
titre = "Revised Edition, 1831"
