audience = "adult"
author = "Mary Wollstonecraft Shelley"
bookid = ""
copyright = "CC BY-NC-SA"
date = "2024"
description = "A horrific story"
imgsize = "1200x q70"
logo = "/uploads/illustration.jpg"
publisher = "Édité par la classe ELD718-2024"
subject = ["horror", "frisson", "fantastique"]
title = "Frankenstein, or the Modern Prometheus"
subtitle = "Revised Edition, 1831"
soustitre = "Revised Edition, 1831"
